codecov:
  require_ci_to_pass: yes
  branch: main

coverage:
  precision: 2
  round: down
  range: "90..100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no
  branches:
    - main
  after_n_builds: 6  # 3 python versions by 2 dbs
